name: "Deploy akhilesh.art to Distributed Press"

on:
  push:
    branches:
      - main # Run the workflow on push to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install dependencies and build the static site (if applicable)
    # Uncomment these lines if you need to build the static files
    # - run: npm ci
    # - run: npm run build

    # Step 4: Publish to Distributed Press
    - name: Publish to Distributed Press
      uses: hyphacoop/actions-distributed-press@v1.1
      with:
        publish_dir: public # The directory with the static files. Update if necessary
        dp_url: https://api.distributed.press/v1 # The DP API instance URL
        refresh_token: ${{ secrets.REFRESH_TOKEN }} # Use the GitHub Secret we set up
        site_url: akhilesh.art # The domain name (should match the domain used when creating the site)
        deploy_http: true # Enable HTTP deployment
        deploy_hyper: true # Enable Hyper deployment
        deploy_ipfs: true # Enable IPFS deployment
